### ISSUE TITLE
System cannot move the file to different disk drive (Cache)

### ISSUE THREAD

**Issue by leonardohra** [PokeAPI/pokepy#54]
I was trying to keep my cache in the same folder of my project, so I tried this:
client = pokepy.V2Client(cache='in_disk', cache_location='cache_pokepy')
The code works, but whenever I make a request 
client.get_pokemon(10)
I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pokepy\api.py", line 272, in memoizer
    cache[key] = func(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\fcache\cache.py", line 267, in __setitem__
    self._write_to_file(filename, value)
  File "C:\Program Files\Python37\lib\site-packages\fcache\cache.py", line 249, in _write_to_file
    rename(tmp, filename)
  File "C:\Program Files\Python37\lib\site-packages\fcache\posixemulation.py", line 95, in rename
    os.rename(src, dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\under\\AppData\\Local\\Temp\\tmp9j5a7863' -> 'cache_pokepy\\pokepy_cache\\39\\cache\\3130'

Apparently it has something to do with [using os.rename to change the file path](https://stackoverflow.com/questions/21116510/python-oserror-winerror-17-the-system-cannot-move-the-file-to-a-different-d), but I'm not sure if that "os.rename" is on your code or something that your code uses.

**Comment by Kronopt** [comment]
Nice catch!
It's an issue with [fcache](https://github.com/tsroten/fcache), one of pokepy's dependencies.

I checked and there actually already is an open [issue](https://github.com/tsroten/fcache/issues/28) for this, so it's been reported.
Although, I don't think the maintainer is active at all...
I bumped the issue anyway. The fix is quite simple, actually.

I could fix this just for pokepy, but it would be better if it was fixed upstream.
I would very much prefer not to have a tweaked version of fcache on the pokepy repository...

I will wait a couple of days.
If there's no update. I'll fix it myself

**Comment by Kronopt** [comment]
@leonardohra, can you please test the fix I made?
You can get the test release with pip:
```sh
pip install -i https://test.pypi.org/simple/ pokepy
```

**Comment by leonardohra** [comment]
Sure, no problems!
I've uninstalled my pokepy
```
pip uninstall pokepy
```

Then I've run the command you've said

```
pip install -i https://test.pypi.org/simple/ pokepy
```

Then I've run python interpreter on my cmd prompt and 
```
import pokepy
```

Then I've got the following error:
```
import pokepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\pokepy\__init__.py", line 24, in <module>
    from .api import V2Client
  File "C:\Program Files\Python37\lib\site-packages\pokepy\api.py", line 18, in <module>
    from .fcache.cache import FileCache
ModuleNotFoundError: No module named 'pokepy.fcache'
```

Did I miss something?

**Comment by Kronopt** [comment]
Sorry, I know what the problem is...
I'll fix it later in the day!

**Comment by leonardohra** [comment]
No problems. I'll test again when its fixed.
Thanks!

**Comment by Kronopt** [comment]
Hey!
Can you please test this one now:
```sh
pip install -i https://test.pypi.org/simple/ pokepy==0.6.1a1
```

Thanks! :)

**Comment by leonardohra** [comment]
Sure.
I did the same thing I've done in my previous comment.
When I've imported pokepy there wasn't any errors and a cache folder was created successfully with 48 subfolders named 0 to 47.
I've used 

```
client.get_pokemon(1)
```

As a test, and the cache file was created successfully.
For me the issue is solved. Thanks!
If you want you can "close" the issue (I don't know if I'm allowed to close it, or if there's something more to be done)

**Comment by Kronopt** [comment]
Nice!
Thank you for taking the time to test this out! :)

I'll upload the new release to pypi in the following hours!
